name: Docker Build & Publish

on: [push]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: agl23/exo-4-4:demo
