name: Job Outputs

on: [push]

jobs:
  prepare_tests:
    runs-on: ubuntu-latest
    outputs:
      HOST: ${{ steps.setup_host.outputs.HOST }}
      DATABASE: ${{ steps.setup_host.outputs.DATABASE }}
    steps:
      - name: setup_host
        id: setup_host
        run: |
          echo "HOST=srv1" >> $GITHUB_OUTPUT
          echo "DATABASE=prep002" >> $GITHUB_OUTPUT

  display_infos:
    needs: prepare_tests
    runs-on: ubuntu-latest
    steps:
      - name: Affiche les valeurs reçues
        run: |
          echo "HOST: ${{ needs.prepare_tests.outputs.HOST }}"
          echo "DATABASE: ${{ needs.prepare_tests.outputs.DATABASE }}"
