name: Tests avec rapport HTML

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python et des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      - name: Lancement des tests avec rapport HTML
        run: |
          pytest --html=rapport_tests.html

      - name: Upload du rapport HTML
        uses: actions/upload-artifact@v4
        with:
          name: rapport-tests
          path: rapport_tests.html
