name: Python Script Workflow

on:
  workflow_dispatch:

jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Exécuter demo.py
        run: python demo.py
