name: Secret Example

on: [push]

jobs:
  confidential_data:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le secret
        run: echo "La valeur de SUPER_SECRET est '${{ secrets.SUPER_SECRET }}'"
