name: Test TLDR Workflow

on:
  workflow_dispatch:

jobs:
  testing_phase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo TLDR à un tag précis
        uses: actions/checkout@v4
        with:
          repository: tldr-pages/tldr-python-client
          ref: '3.1.0'  # tag spécifique

      - name: Setup Python 3.10
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install jq
          pip install -r requirements.txt

      - name: Installer pytest
        run: pip install pytest

      - name: Lancer les tests
        run: pytest
